### ISSUE TITLE
Submitted files are out of sequence

### ISSUE THREAD

**Issue by JuTz0r** [botherder/viper#206]
When submitting files via the API and reviewing them in the web UI, the results are out of numerical sequence.

**Comment by JuTz0r** [comment]
The issue seems to be the sort is going off of the file created time and not the ID.

**Comment by deralexxx** [comment]
yeah can confirm that, looks like it is because of             rows = session.query(Malware).order_by(Malware.created_at.desc()).limit(value).offset(offset)

and if you push multiple files at almost the same time the return for CLI "find latest" is wrong as well as the table in web.py (which are both using the same method, will provide a fix in a minute
